version: "3.8"

services:
  backend:
    # 빌드 이미지의 이름을 명시적으로 지정
    image: areuhotspring
    build:
      context: ./server
    container_name: areuhot-spring-container
    ports:
      - "8080:8080"
    # 사용자가 중지하지 않는 이상 자동 재시작
    restart: unless-stopped
    volumes:
      - backend_data:/app/data # .lck 파일 저장 경로
    networks:
      - app-network
    command: sh -c "chmod -R 777 /app/data && sleep 1 && java -Duser.timezone=Asia/Seoul -jar app.jar"

  frontend:
    image: areuhotreact
    build:
      context: ./frontend
    container_name: areuhot-react-container
    ports:
      - "5173:80"
    # volumes:
    #   - ./frontend/dist:/usr/share/nginx/html # 빌드 결과물 호스트->컨테이너 공유
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_data:
