mpu6050driver:
  ros__parameters:
    frame_id: 'imu_link'
    
    calibrate: true
    
    # I2C Device path
    port: "/dev/i2c-1"

    # measurement ranges (match MPU6050Sensor::GyroRange and ::AccelRange enums)
    gyro_range: 0         # GYR_250_DEG_S
    accel_range: 0        # ACC_2_G

    # digital low‐pass filter bandwidth (match MPU6050Sensor::DlpfBandwidth)
    dlpf_bandwidth: 0     # DLPF_260_HZ

    # any offsets you measured during calibration
    gyro_x_offset: 0.0
    gyro_y_offset: 0.0
    gyro_z_offset: 0.0
    accel_x_offset: 0.0
    accel_y_offset: 0.0
    accel_z_offset: 0.0

    # this node’s internal “frequency” parameter (unused in example)
    frequency: 100        # Hz

