controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.6
      max_linear_accel: 1.0
      max_linear_decel: -1.0
      min_slowdown_velocity: 0.6
      regulated_linear_scaling_min_speed: 0.6
      use_cost_regulated_linear_velocity_scaling: true
      use_velocity_scaled_lookahead_dist: true
      lookahead_dist: 1.0
      min_lookahead_dist: 0.35
      max_lookahead_dist: 1.5
      transform_tolerance: 0.2
      lookahead_time: 0.8
      rotate_to_heading_angular_vel: 1.8
      max_angular_accel: 2.0
      min_turning_radius: 1.2
      cost_scaling_dist: 0.6
      cost_scaling_gain: 1.0
      allow_reversing: true
      use_rotate_to_heading: false
      use_intermediate_points: true

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 2.0
    planner_plugins: ["GridBased"]
    #planner_plugins: ["SmacHybrid"]
    #SmacHybrid:
    GridBased:
      #plugin: "nav2_navfn_planner/NavfnPlanner"
      #tolerance: 0.2
      #allow_unknown: true # hmm
      #minimum_turning_radius: 0.53
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.2
      allow_unknown: true
      motion_model_for_search: "REEDS_SHEPP"  # ← 전/후진 허용
      allow_reverse: true                     # ← 후진 전개 허용
      minimum_turning_radius: 1.2             # ← 컨트롤러의 min_turning_radius와 **같게**
      angle_quantization_bins: 72             # (권장) 회전 해상도
      lookup_table_size: 20.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 6
      height: 6
      resolution: 0.025
      footprint: '[[0.30, 0.11], [0.30, -0.11], [-0.06, -0.1], [-0.06, 0.1]]'
      update_frequency: 10.0
      publish_frequency: 10.0
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          marking: true
          clearing: true
          obstacle_range: 3.5
          raytrace_range: 4.5
          inf_is_valid: true
        combination_method: 1

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5
        cost_scaling_factor: 3.0

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_link
      update_frequency: 2.0
      publish_frequency: 1.0
      resolution: 0.025
      track_unknown_space: true
      rolling_window: true
      width: 20
      height: 20
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        subscribe_to_updates: true
        map_subscribe_transient_local: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          marking: true
          clearing: true
          obstacle_range: 3.5
          raytrace_range: 4.5
          inf_is_valid: true # hmm
        combination_method: 1

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5
        cost_scaling_factor: 3.0

